#!/usr/bin/env node

/**************************************************************************************************
 * hoobs-image                                                                                    *
 * Copyright (C) 2020 HOOBS                                                                       *
 *                                                                                                *
 * This program is free software: you can redistribute it and/or modify                           *
 * it under the terms of the GNU General Public License as published by                           *
 * the Free Software Foundation, either version 3 of the License, or                              *
 * (at your option) any later version.                                                            *
 *                                                                                                *
 * This program is distributed in the hope that it will be useful,                                *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                                 *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                  *
 * GNU General Public License for more details.                                                   *
 *                                                                                                *
 * You should have received a copy of the GNU General Public License                              *
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.                          *
 **************************************************************************************************/

const OS = require("os");
const Semver = require("semver");
const Program = require("commander");
const Inquirer = require("inquirer");
const Loco = require("loco-api-js");
const { join } = require("path");
const { execSync } = require("child_process");
const { MongoClient } = require("mongodb");

const {
    existsSync,
    readFileSync,
    writeFileSync,
    unlinkSync,
    mkdirSync,
    rmSync,
} = require("fs");

const root = join(__dirname, "../");
const pjson = JSON.parse(readFileSync(join(root, "package.json")).toString());

const prompt = Inquirer.createPromptModule();
const user = OS.userInfo();

function execLocal(command, options) {
    try {
        return execSync(command, options || { cwd: root, stdio: "inherit" }).toString().trim();
    } catch (_error) {
        return "";
    }
}

function existsLocal(path) {
    return existsSync(path);
}

function existsWaterfall(root, repo, filename) {
    switch (repo) {
        case "stable":
            if (!existsLocal(join(root, "repo/deb/stable", filename))) return false;
            if (!existsLocal(join(root, "repo/deb/edge", filename))) return false;
            if (!existsLocal(join(root, "repo/deb/bleeding", filename))) return false;

            break;

        case "edge":
            if (!existsLocal(join(root, "repo/deb/edge", filename))) return false;
            if (!existsLocal(join(root, "repo/deb/bleeding", filename))) return false;

            break;

        default:
            if (!existsLocal(join(root, "repo/deb/edge", filename))) return false;
            if (!existsLocal(join(root, "repo/deb/bleeding", filename))) return false;

            break;
    }

    return true;
}

function downloadRemote(credentials, source, destination) {
    execLocal(`sshpass -p '${credentials.pass}' scp ${credentials.user}@${credentials.host}:${source} ${destination}`);
}

function createRelease(repo, title, version, files, notes, beta) {
    if (beta) {
        execLocal(`gh release create v${version} ${files} -p -t '${title} ${version}' -n '${notes}'`, { cwd: repo, stdio: "inherit" });
    } else {
        execLocal(`gh release create v${version} ${files} -t '${title} ${version}' -n '${notes}'`, { cwd: repo, stdio: "inherit" });
    }
}

function checkEnviornment() {
    const signing = execLocal("command -v dpkg-sig", { stdio: "pipe" }).toString().replace(/\n/g, "").trim();
    const sshpass = execLocal("command -v sshpass", { stdio: "pipe" }).toString().replace(/\n/g, "").trim();
    const docker = execLocal("command -v docker", { stdio: "pipe" }).toString().replace(/\n/g, "").trim();
    const reprepro = execLocal("command -v reprepro", { stdio: "pipe" }).toString().replace(/\n/g, "").trim();
    const gh = execLocal("command -v gh", { stdio: "pipe" }).toString().replace(/\n/g, "").trim();

    if (process.platform === "linux" && (!signing || signing === "")) {
        console.log("dpkg-sig is not installed, https://git.io/JOKhF");

        return false;
    }

    if (process.platform === "linux" && (!sshpass || sshpass === "")) {
        console.log("sshpass is not installed, https://git.io/JOKhF");

        return false;
    }

    if (process.platform === "linux" && (!docker || docker === "")) {
        console.log("docker is not installed, https://git.io/JOKhF");

        return false;
    }

    if (process.platform === "linux" && (!reprepro || reprepro === "")) {
        console.log("reprepro is not installed, https://git.io/JOKhF");

        return false;
    }

    if (process.platform === "linux" && (!gh || gh === "")) {
        console.log("gh is not installed, https://git.io/JOKhF");

        return false;
    }

    if (
        !existsLocal(join(root, "./sdk", "package.json"))
     || !existsLocal(join(root, "./cli", "package.json"))
     || !existsLocal(join(root, "./gui", "package.json"))
     || !existsLocal(join(root, "./hoobsd", "package.json"))
     || !existsLocal(join(root, "./desktop", "package.json"))
     || !existsLocal(join(root, "./migration", "package.json"))
    ) {
        console.log("workspace not initilized, https://git.io/JOKhF");

        return false;
    }

    if (!existsLocal(join(root, "./hoobsd", ".env.production"))) {
        console.log("missing hoobsd production enviornment file, https://git.io/JOKhF");

        return false;
    }

    if (!existsLocal(join(root, "./gui", ".env.production"))) {
        console.log("missing hoobs gui production enviornment file, https://git.io/JOKhF");

        return false;
    }

    if (!existsLocal(join(root, "./security", "credentials.json"))) {
        console.log("missing security repository, https://git.io/JOKhF");

        return false;
    }

    return true;
}

async function updateLocalization(credentials) {
    const loco = new Loco(credentials.loco);
    const locales = await loco.getLocales();
    const source = JSON.parse(readFileSync(join(root, "./lang", "strings.json")));
    const keys = Object.keys(source);

    keys.sort();

    const missing = {};

    if (existsSync(join(root, "./lang", "missing.json"))) unlinkSync(join(root, "./lang", "missing.json"));

    for (let i = 0; i < locales.length; i += 1) {
        const local = locales[i].code.split("-")[0];
        const output = {};

        output[local] = {};

        if (existsSync(join(root, "./gui/src/lang/locals", `${local}.json`))) unlinkSync(join(root, "./gui/src/lang/locals", `${local}.json`));
        if (existsSync(join(root, "./desktop/src/lang/locals", `${local}.json`))) unlinkSync(join(root, "./desktop/src/lang/locals", `${local}.json`));

        if (local === "en") {
            for (let j = 0; j < keys.length; j += 1) {
                output[local][keys[j]] = (source[keys[j]] || "").trim();
            }
        } else {
            const resource = (await loco.exportLocale(locales[i].code));

            for (let j = 0; j < keys.length; j += 1) {
                if (resource[keys[j]] === undefined) missing[keys[j]] = (source[keys[j]] || "").trim();

                output[local][keys[j]] = (resource[keys[j]] || source[keys[j]] || "").trim();
            }
        }

        console.log(`updated localization "${local}"`);

        writeFileSync(join(root, "./gui/src/lang/locals", `${local}.json`), JSON.stringify(output, null, 4));
        writeFileSync(join(root, "./desktop/src/lang/locals", `${local}.json`), JSON.stringify(output, null, 4));
    }

    if (Object.keys(missing).length > 0) console.log("missing language strings need to up uploaded, https://localise.biz/session/auth/login");

    writeFileSync(join(root, "./lang", "missing.json"), JSON.stringify(missing, null, 4));

    if (existsSync(join(root, "./gui/src/lang", "countries.json"))) unlinkSync(join(root, "./gui/src/lang", "countries.json"));
    if (existsSync(join(root, "./desktop/src/lang", "emojis.json"))) unlinkSync(join(root, "./desktop/src/lang", "emojis.json"));

    execLocal(`cp ${join(root, "./lang", "countries.json")} ${join(root, "./gui/src/lang", "countries.json")}`);
    execLocal(`cp ${join(root, "./lang", "countries.json")} ${join(root, "./desktop/src/lang", "countries.json")}`);

    execLocal(`cp ${join(root, "./lang", "emojis.json")} ${join(root, "./gui/src/lang", "emojis.json")}`);
    execLocal(`cp ${join(root, "./lang", "emojis.json")} ${join(root, "./desktop/src/lang", "emojis.json")}`);
}

async function buildPackages(repo, credentials, version, built) {
    pjson.version = version;

    writeFileSync(join(root, "package.json"), JSON.stringify(pjson, null, 4));

    const working = {
        sdk: JSON.parse(readFileSync(join(root, "./sdk", "package.json")).toString()),
        cli: JSON.parse(readFileSync(join(root, "./cli", "package.json")).toString()),
        gui: JSON.parse(readFileSync(join(root, "./gui", "package.json")).toString()),
        hoobsd: JSON.parse(readFileSync(join(root, "./hoobsd", "package.json")).toString()),
        desktop: JSON.parse(readFileSync(join(root, "./desktop", "package.json")).toString()),
        migration: JSON.parse(readFileSync(join(root, "./migration", "package.json")).toString()),
    }

    let darwin;

    if (!existsLocal(join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.exe`)) || !existsLocal(join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.dmg`))) {
        let confirm = false;

        confirm = (await prompt([{
            type: "confirm",
            name: "confirm",
            default: true,
            message: "Do you want to build HOOBS desktop",
            format: (value) => value.toLowerCase(),
        }])).confirm;

        if (confirm) {
            try {
                darwin = JSON.parse(readFileSync(join(OS.homedir(), "hoobs.darwin.build")).toString());
            } catch (_error) {
                darwin = undefined;
            }
    
            if (darwin) {
                confirm = (await prompt([{
                    type: "confirm",
                    name: "confirm",
                    default: true,
                    message: "Use stored build credentials",
                    format: (value) => value.toLowerCase(),
                }])).confirm;
            }
    
            if (!darwin || !confirm) {
                darwin = await prompt([{
                    type: "string",
                    name: "host",
                    message: "Enter the macOS build host",
                }, {
                    type: "string",
                    name: "user",
                    message: "Username",
                }, {
                    type: "password",
                    name: "pass",
                    message: "Password",
                }, {
                    type: "string",
                    name: "path",
                    default: "~/Projects/HOOBS",
                    message: "Project path",
                }, {
                    type: "string",
                    name: "gituser",
                    message: "GitHub Username",
                }, {
                    type: "password",
                    name: "gitpass",
                    message: "GitHub Password",
                }]);
            }

            if (darwin) {
                writeFileSync(join(OS.homedir(), "hoobs.darwin.build"), JSON.stringify(darwin, null, 4));
            } else if (existsSync(join(OS.homedir(), "hoobs.darwin.build"))) {
                unlinkSync(join(OS.homedir(), "hoobs.darwin.build"));
            }
        }
    }

    if (!existsLocal(join(root, "repo/npm", `hoobs-sdk-v${working.sdk.version}.tgz`))) {
        console.log("building hoobs sdk");
        execLocal("bin/build --lint --pack", { cwd: join(root, "./sdk"), stdio: "inherit" });
        built.push("sdk");
    }

    if (!existsWaterfall(root, repo, `hoobs-cli-v${working.cli.version}.deb`)) {
        console.log("building hoobs cli");
        execLocal(`bin/build --repo ${repo} --lint --pack`, { cwd: join(root, "./cli"), stdio: "inherit" });
        built.push("cli");
    }

    if (!existsLocal(join(root, "repo/npm", `hoobs-migration-v${working.migration.version}.tgz`))) {
        console.log("building hoobs migration tool");
        execLocal("bin/build --lint --pack", { cwd: join(root, "./migration"), stdio: "inherit" });
        built.push("migration");
    }

    if (!existsWaterfall(root, repo, `hoobsd-v${working.hoobsd.version}.deb`)) {
        console.log("building hoobsd");
        execLocal(`bin/build --repo ${repo} --lint --pack`, { cwd: join(root, "./hoobsd"), stdio: "inherit" });
        built.push("hoobsd");
    }

    if (!existsWaterfall(root, repo, `hoobs-gui-v${working.gui.version}.deb`)) {
        console.log("building hoobs gui");

        await updateLocalization(credentials);

        execLocal(`bin/build --repo ${repo} --lint --pack`, { cwd: join(root, "./gui"), stdio: "inherit" });
        built.push("gui");
    }

    if (darwin && (!existsLocal(join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.exe`)) || !existsLocal(join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.dmg`)))) {
        console.log("building hoobs desktop");

        downloadRemote(darwin, join(darwin.path, "repo/bin", `hoobs-desktop-v${working.desktop.version}.exe`), join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.exe`));
        downloadRemote(darwin, join(darwin.path, "repo/bin", `hoobs-desktop-v${working.desktop.version}.dmg`), join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.dmg`));

        built.push("desktop");
    }

    if (!existsWaterfall(root, repo, `hoobs-v${pjson.version}.deb`)) {
        console.log("building bundle");

        if (existsLocal(join(root, "dist"))) execLocal(`rm -fR ${join(root, "dist")}`)

        mkdirSync(join(root, "dist"));
        mkdirSync(join(root, "dist/DEBIAN"));

        let control = "";

        control += "Package: hoobs\n";
        control += `Version: ${pjson.version}\n`;
        control += "Section: base\n";
        control += "Priority: optional\n";
        control += "Architecture: all\n";
        control += "Depends: hoobs-cli (>= 4.0.0), hoobsd (>= 4.0.0), hoobs-gui (>= 4.0.0)\n";
        control += "Maintainer: HOOBS Maintainers <info@hoobs.org>\n";
        control += "Homepage: https://hoobs.org\n";
        control += "Description: Build your Smart Home with HOOBS. Connect over 2,000 Accessories to your favorite Ecosystem.\n";

        writeFileSync(join(root, "dist/DEBIAN/control"), control);
        execLocal(`cp ${join(root, "image/scripts", "postinst")} ${join(root, "dist/DEBIAN", "postinst")}`);
        execLocal(`chmod 755 ${join(root, "dist/DEBIAN", "postinst")}`);
        execLocal("dpkg-deb --build dist");

        switch (repo) {
            case "stable":
                if (existsLocal(join(root, "repo/deb/stable", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/stable", `hoobs-v${pjson.version}.deb`));
                if (existsLocal(join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`));
                if (existsLocal(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`));

                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/stable", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);

                execLocal(`rm -f ${join(root, "dist.deb")}`);

                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/stable", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);
                break;
    
            case "edge":
                if (existsLocal(join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`));
                if (existsLocal(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`));

                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);

                execLocal(`rm -f ${join(root, "dist.deb")}`);

                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);
                break;
    
            default:
                if (existsLocal(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`))) unlinkSync(join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`));

                execLocal(`cp ${join(root, "dist.deb")} ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);
                execLocal(`rm -f ${join(root, "dist.deb")}`);
                execLocal(`dpkg-sig --sign builder ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`);
                break;
        }

        if (existsLocal(join(root, "dist"))) execLocal(`rm -fR ${join(root, "dist")}`);
    }
}

function buildImage(node, built) {
    const working = {
        connect: JSON.parse(readFileSync(join(root, "./connect", "package.json")).toString()),
    }

    if (!existsLocal(join(root, "repo/src", `hoobs-connect-v${working.connect.version}.tar.gz`))) {
        console.log("building hoobs connect");

        execLocal("bin/build", { cwd: join(root, "./connect"), stdio: "inherit" });
    }

    if (!existsLocal(join(root, "repo/img", `hoobs-v${pjson.version}.zip`))) {
        console.log("building image");

        execLocal("sudo docker rm -v hoobs-image", { cwd: join(root, "image"), stdio: "ignore" });

        if (existsLocal(join(root, "hoobs"))) rmSync(join(root, "image/hoobs.conf"));
        if (!existsLocal(join(root, "./image/stage3/01-wifi-connect/files"))) mkdirSync(join(root, "./image/stage3/01-wifi-connect/files"));

        execLocal(`cp ${join(root, "repo/src", `hoobs-connect-v${working.connect.version}.tar.gz`)} ${join(root, "./image/stage3/01-wifi-connect/files", "hoobs-connect.tar.gz")}`);

        let variables = "";

        variables += "IMG_NAME=\"HOOBS\"\n";
        variables += `IMG_FILENAME="hoobs-${pjson.version}"\n`;
        variables += `ZIP_FILENAME="hoobs-${pjson.version}"\n`;
        variables += `NODE_RELEASE="${node}"\n`;
        variables += "WIFI_SSID=HOOBS\n";
        variables += "LOCALE_DEFAULT=\"en_US.UTF-8\"\n";
        variables += "KEYBOARD_KEYMAP=\"us\"\n";
        variables += "KEYBOARD_LAYOUT=\"English (US)\"\n";
        variables += "TIMEZONE_DEFAULT=\"America/Denver\"\n";
        variables += "TARGET_HOSTNAME=hoobs\n";
        variables += "FIRST_USER_NAME=hoobs\n";
        variables += "FIRST_USER_PASS=hoobsadmin\n";
        variables += "ENABLE_SSH=1\n";
        variables += "STAGE_LIST=\"stage0 stage1 stage2 stage3 stage4 stage5\"\n";

        writeFileSync(join(root, "image/hoobs.conf"), variables);

        execLocal(`${join(root, "image/container")} -c ${join(root, "image/hoobs.conf")}`, { cwd: join(root, "image"), stdio: "inherit" });

        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}.zip`)}`, { cwd: join(root, "image"), stdio: "inherit" });
        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}-box.zip`)}`, { cwd: join(root, "image"), stdio: "inherit" });
        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}-headless.zip`)}`, { cwd: join(root, "image"), stdio: "inherit" });
        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}.info`)}`, { cwd: join(root, "image"), stdio: "inherit" });
        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}-box.info`)}`, { cwd: join(root, "image"), stdio: "inherit" });
        execLocal(`sudo chown ${user.uid}:${user.gid} ${join(root, "image/deploy", `hoobs-${pjson.version}-headless.info`)}`, { cwd: join(root, "image"), stdio: "inherit" });

        if (existsLocal(join(root, "repo/img", `hoobs-v${pjson.version}.zip`))) unlinkSync(join(root, "repo/img", `hoobs-v${pjson.version}.zip`))
        if (existsLocal(join(root, "repo/img", `hoobs-box-v${pjson.version}.zip`))) unlinkSync(join(root, "repo/img", `hoobs-box-v${pjson.version}.zip`))
        if (existsLocal(join(root, "repo/img", `hoobsd-v${pjson.version}.zip`))) unlinkSync(join(root, "repo/img", `hoobsd-v${pjson.version}.zip`))
        if (existsLocal(join(root, "repo/img", `hoobs-v${pjson.version}.info`))) unlinkSync(join(root, "repo/img", `hoobs-v${pjson.version}.info`))
        if (existsLocal(join(root, "repo/img", `hoobs-box-v${pjson.version}.info`))) unlinkSync(join(root, "repo/img", `hoobs-box-v${pjson.version}.info`))
        if (existsLocal(join(root, "repo/img", `hoobsd-v${pjson.version}.info`))) unlinkSync(join(root, "repo/img", `hoobsd-v${pjson.version}.info`))

        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}.zip`)} ${join(root, "repo/img", `hoobs-v${pjson.version}.zip`)}`);
        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}-box.zip`)} ${join(root, "repo/img", `hoobs-box-v${pjson.version}.zip`)}`);
        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}-headless.zip`)} ${join(root, "repo/img", `hoobsd-v${pjson.version}.zip`)}`);
        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}.info`)} ${join(root, "repo/img", `hoobs-v${pjson.version}.info`)}`);
        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}-box.info`)} ${join(root, "repo/img", `hoobs-box-v${pjson.version}.info`)}`);
        execLocal(`sudo mv ${join(root, "image/deploy", `hoobs-${pjson.version}-headless.info`)} ${join(root, "repo/img", `hoobsd-v${pjson.version}.info`)}`);

        if (existsLocal(join(root, "image/deploy"))) execLocal(`sudo rm -fR ${join(root, "image/deploy")}`);

        built.push("image");
        built.push("server");
        built.push("box");
    }
}

async function publishPackage(repo, credentials, built) {
    const working = {
        sdk: JSON.parse(readFileSync(join(root, "./sdk", "package.json")).toString()),
        cli: JSON.parse(readFileSync(join(root, "./cli", "package.json")).toString()),
        gui: JSON.parse(readFileSync(join(root, "./gui", "package.json")).toString()),
        hoobsd: JSON.parse(readFileSync(join(root, "./hoobsd", "package.json")).toString()),
        desktop: JSON.parse(readFileSync(join(root, "./desktop", "package.json")).toString()),
        migration: JSON.parse(readFileSync(join(root, "./migration", "package.json")).toString()),
    }

    const exists = {
        sdk: execLocal(`yarn info @hoobs/sdk version | grep ${working.sdk.version}`, { cwd: root }) === working.sdk.version,
        migration: execLocal(`yarn info @hoobs/migration version | grep ${working.migration.version}`, { cwd: root }) === working.migration.version,
    }

    if (!exists.sdk) {
        console.log("publishing hoobs sdk");
        execLocal(`yarn publish --access public --new-version ${working.sdk.version}`, { cwd: join(root, "./sdk"), stdio: "inherit" });
    }

    if (!exists.migration) {
        console.log("publishing hoobs migration tool");
        execLocal(`yarn publish --access public --new-version ${working.migration.version}`, { cwd: join(root, "./migration"), stdio: "inherit" });
    }

    console.log("updating repository");

    switch (repo) {
        case "stable":
            if (built.indexOf("cli") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/stable", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/stable"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("hoobsd") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/stable", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/stable"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("gui") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/stable", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/stable"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("image") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/stable", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/stable"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/stable"), stdio: "inherit" });
            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            break;

        case "edge":
            if (built.indexOf("cli") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("hoobsd") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("gui") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            if (built.indexOf("image") >= 0) {
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/edge", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
                execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            }

            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/edge"), stdio: "inherit" });
            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            break;

        default:
            if (built.indexOf("cli") >= 0) execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-cli-v${working.cli.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            if (built.indexOf("hoobsd") >= 0) execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobsd-v${working.hoobsd.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            if (built.indexOf("gui") >= 0) execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-gui-v${working.gui.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            if (built.indexOf("image") >= 0) execLocal(`reprepro includedeb buster ${join(root, "repo/deb/bleeding", `hoobs-v${pjson.version}.deb`)}`, { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });

            execLocal("reprepro list buster", { cwd: join(root, "repo/deb/bleeding"), stdio: "inherit" });
            break;
    }

    if (built.indexOf("gui") >= 0 || built.indexOf("hoobsd") >= 0 || built.indexOf("cli") >= 0 || built.indexOf("image") >= 0) {
        console.log("syncing repository");

        execLocal("git pull", { cwd: join(root, "repo"), stdio: "inherit" });
        execLocal("git add --all", { cwd: join(root, "repo"), stdio: "inherit" });
        execLocal("git commit -m 'image push'", { cwd: join(root, "repo"), stdio: "inherit" });
        execLocal("git push", { cwd: join(root, "repo"), stdio: "inherit" });
    }

    if (repo === "edge" || repo === "stable") {
        const beta = repo === "edge" || repo === "bleeding";
        const client = new MongoClient(credentials.db, { useUnifiedTopology: true });

        await client.connect();

        const database = client.db("support");
        const releases = database.collection("releases");

        if (built.indexOf("sdk") >= 0) {
            createRelease(
                join(root, "sdk"),
                "HOOBS SDK",
                working.sdk.version,
                join(root, "repo/npm", `hoobs-sdk-v${working.sdk.version}.tgz`),
                "HOOBS SDK for building applications that talk with the HOOBS API.\n\n* Big fixes",
                false,
            );
        }

        if (built.indexOf("migration") >= 0) {
            createRelease(
                join(root, "migration"),
                "HOOBS Migration",
                working.migration.version,
                join(root, "repo/npm", `hoobs-migration-v${working.migration.version}.tgz`),
                "HOOBS 4 Migration Utility.\n\n* Big fixes",
                false,
            );
        }

        if (built.indexOf("desktop") >= 0) {
            await releases.updateOne({ application: "desktop", latest: true, beta }, { $set: { latest: false } }, { upsert: true });

            if (!beta) await releases.updateOne({ application: "desktop", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });

            await releases.insertOne({
                application: "desktop",
                version: working.desktop.version,
                published: new Date(),
                latest: true,
                download_win: `https://github.com/hoobs-org/desktop/releases/download/v${working.desktop.version}/hoobs-desktop-v${working.desktop.version}.exe`,
                download_mac: `https://github.com/hoobs-org/desktop/releases/download/v${working.desktop.version}/hoobs-desktop-v${working.desktop.version}.dmg`,
                beta,
            });

            createRelease(
                join(root, "desktop"),
                "HOOBS Desktop",
                working.desktop.version,
                join(root, "repo/bin", `hoobs-desktop-v${working.desktop.version}.*`),
                "HOOBS Desktop Application.\n\n* Big fixes",
                beta,
            );
        }
                
        if (built.indexOf("gui") >= 0) {
            await releases.updateOne({ application: "gui", latest: true, beta }, { $set: { latest: false } }, { upsert: true });

            if (!beta) await releases.updateOne({ application: "gui", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });

            await releases.insertOne({
                application: "gui",
                version: working.gui.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/gui/releases/download/v${working.gui.version}/hoobs-gui-v${working.gui.version}.tar.gz`,
                beta,
            });

            createRelease(
                join(root, "gui"),
                "HOOBS Web Interface",
                working.gui.version,
                join(root, "repo/src", `hoobs-gui-v${working.gui.version}.tar.gz`),
                "Interface component for the certified HOOBS stack.\n\n* Big fixes",
                beta,
            );
        }

        if (built.indexOf("hoobsd") >= 0) {
            await releases.updateOne({ application: "hoobsd", latest: true, beta }, { $set: { latest: false } }, { upsert: true });

            if (!beta) await releases.updateOne({ application: "hoobsd", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });

            await releases.insertOne({
                application: "hoobsd",
                version: working.hoobsd.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/hoobsd/releases/download/v${working.hoobsd.version}/hoobsd-v${working.hoobsd.version}.tar.gz`,
                beta,
            });

            createRelease(
                join(root, "hoobsd"),
                "HOOBS Daemon",
                working.hoobsd.version,
                join(root, "repo/src", `hoobsd-v${working.hoobsd.version}.tar.gz`),
                "Server component for the certified HOOBS smart home stack.\n\n* Big fixes",
                beta,
            );
        }

        if (built.indexOf("cli") >= 0) {
            await releases.updateOne({ application: "hbs", latest: true, beta }, { $set: { latest: false } }, { upsert: true });
            await releases.updateOne({ application: "setup", latest: true, beta: false }, { $set: { latest: false } }, { upsert: true });

            if (!beta) await releases.updateOne({ application: "hbs", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });

            await releases.insertOne({
                application: "hbs",
                version: working.cli.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/cli/releases/download/v${working.cli.version}/hoobs-cli-v${working.cli.version}.tar.gz`,
                beta,
            });

            await releases.insertOne({
                application: "setup",
                version: working.cli.version,
                published: new Date(),
                latest: true,
                download: `https://dl.hoobs.org/stable`,
                beta: false,
            });

            createRelease(
                join(root, "cli"),
                "HOOBS Command Line",
                working.cli.version,
                join(root, "repo/src", `hoobs-cli-v${working.cli.version}.tar.gz`),
                "Command line interface for the certified HOOBS smart home stack.\n\n* Big fixes",
                beta,
            );
        }
    }

    return;
}

async function publishImage(repo, credentials, built) {
    if (repo === "edge" || repo === "stable") {
        const beta = repo === "edge" || repo === "bleeding";
        const client = new MongoClient(credentials.db, { useUnifiedTopology: true });

        await client.connect();

        const database = client.db("support");
        const releases = database.collection("releases");

        if (built.indexOf("image") >= 0 || built.indexOf("server") >= 0 || built.indexOf("box") >= 0) {
            await releases.updateOne({ application: "image", latest: true, beta }, { $set: { latest: false } }, { upsert: true });
            await releases.updateOne({ application: "server", latest: true, beta }, { $set: { latest: false } }, { upsert: true });
            await releases.updateOne({ application: "box", latest: true, beta }, { $set: { latest: false } }, { upsert: true });

            if (!beta) {
                await releases.updateOne({ application: "image", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });
                await releases.updateOne({ application: "server", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });
                await releases.updateOne({ application: "box", latest: true, beta: true }, { $set: { latest: false } }, { upsert: true });
            }

            await releases.insertOne({
                application: "image",
                version: pjson.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/repo/releases/download/v${pjson.version}/hoobs-v${pjson.version}.zip`,
                beta,
            });

            await releases.insertOne({
                application: "server",
                version: pjson.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/repo/releases/download/v${pjson.version}/hoobsd-v${pjson.version}.zip`,
                beta,
            });

            await releases.insertOne({
                application: "box",
                version: pjson.version,
                published: new Date(),
                latest: true,
                download: `https://github.com/hoobs-org/repo/releases/download/v${pjson.version}/hoobs-box-v${pjson.version}.zip`,
                beta,
            });

            createRelease(
                join(root, "repo"),
                "HOOBS",
                pjson.version,
                join(root, "repo/img", `hoobs*-v${pjson.version}.*`),
                "HOOBS image for Raspberry Pi.\n\n* Big fixes",
                beta,
            );
        }
    }

    return;
}

Program.version(pjson.version, "-v, --version", "output the current version")
    .allowUnknownOption();

Program.command("release")
    .description("build hoobs image")
    .action(() => {
        if (process.platform === "linux" && checkEnviornment()) {
            const credentials = require("../security/credentials.json");

            prompt([{
                type: "list",
                name: "repo",
                message: "Select the repo to publish to",
                default: "edge",
                choices: [{
                    name: "Stable",
                    value: "stable"
                }, {
                    name: "Edge",
                    value: "edge"
                }, {
                    name: "Bleeding",
                    value: "bleeding"
                }],
            }, {
                type: "string",
                name: "version",
                default: pjson.version,
                message: "Enter the desired version",
                validate: (value) => {
                    if (!Semver.valid(value)) return "invalid version";

                    return true;
                },
            }, {
                type: "string",
                name: "node",
                default: "14",
                message: "Select node major version",
                validate: (value) => {
                    if (Number.isNaN(parseInt(value, 10))) return "invalid version";

                    return true;
                },
            }]).then(async (result) => {
                const built = [];

                await buildPackages(result.repo, credentials, result.version, built);
                await publishPackage(result.repo, credentials, built);

                buildImage(result.node, built);

                await publishImage(result.repo, credentials, built);

                process.exit();
            });
        }
    });

Program.command("locals")
    .description("update localization")
    .action(() => {
        if (checkEnviornment()) {
            const credentials = require("../security/credentials.json");

            updateLocalization(credentials).finally(() => {
                process.exit();
            });
        }
    });

Program.parse(process.argv);
